export const START_LOADING = 'START_LOADING'
export const FINISH_LOADING = 'FINISH_LOADING'

export const FETCH_LIST_SUCESS = 'FETCH_LIST_SUCESS'
export const FETCH_DETAIL_SUCESS = 'FETCH_DETAIL_SUCESS'
export const FETCH_POST_SUCESS = 'FETCH_POST_SUCESS'
export const FETCH_DELETE_SUCESS = 'FETCH_DELETE_SUCESS'
export const FETCH_PUT_SUCESS = 'FETCH_PUT_SUCESS'